//===----------------------------------------------------------------------===//
// SoftmaxMicroOpts: post-LICM micro-optimizations for softmax patterns
// - Fold exp2(log2(e) * x) -> exp(x)
// - Lower divf(X, broadcast(S)) -> mulf(X, broadcast(recip(S)))
// These are local rewrites that don't move ops across loop boundaries.
//===----------------------------------------------------------------------===//

#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Math/IR/Math.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/Pass/Pass.h"
#include "llvm/Support/Casting.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "triton/Dialect/Triton/IR/Dialect.h"
#include "triton/Dialect/Triton/Transforms/Passes.h"

using namespace mlir;

namespace mlir {
namespace triton {

#define GEN_PASS_DEF_TRITONSOFTMAXMICROOPTS
#include "triton/Dialect/Triton/Transforms/Passes.h.inc"

namespace {

static bool isSplatFloat(Value v, double &valOut) {
  if (auto cst = v.getDefiningOp<arith::ConstantOp>()) {
    if (auto dense = dyn_cast_or_null<DenseElementsAttr>(cst.getValue())) {
      if (dense.isSplat()) {
        // Handle both float and half element types
        APFloat apf = dense.getSplatValue<APFloat>();
        valOut = apf.convertToDouble();
        return true;
      }
    }
  }
  return false;
}

// exp2(log2(e) * x) -> exp(x)
struct Exp2MulLog2EToExp : public OpRewritePattern<math::Exp2Op> {
  using OpRewritePattern<math::Exp2Op>::OpRewritePattern;
  LogicalResult matchAndRewrite(math::Exp2Op op,
                                PatternRewriter &rewriter) const override {
    auto mul = op.getOperand().getDefiningOp<arith::MulFOp>();
    if (!mul)
      return failure();

    // Accept either side being the constant
    double c = 0.0;
    Value x;
    if (isSplatFloat(mul.getLhs(), c)) {
      x = mul.getRhs();
    } else if (isSplatFloat(mul.getRhs(), c)) {
      x = mul.getLhs();
    } else {
      return failure();
    }

    constexpr double LOG2E = 1.4426950408889634; // log2(e)
    constexpr double REL_EPS = 1e-6;
    if (std::abs(c - LOG2E) > REL_EPS * std::abs(LOG2E))
      return failure();

    auto newExp = rewriter.create<math::ExpOp>(op.getLoc(), x);
    rewriter.replaceOp(op, newExp.getResult());
    // Let DCE/CSE clean up dead mul/constants if unused.
    return success();
  }
};

// divf(X, broadcast(S)) -> mulf(X, broadcast(recip(S)))
struct DivToMulRecip : public OpRewritePattern<arith::DivFOp> {
  using OpRewritePattern<arith::DivFOp>::OpRewritePattern;
  LogicalResult matchAndRewrite(arith::DivFOp op,
                                PatternRewriter &rewriter) const override {
    Value lhs = op.getLhs();
    Value rhs = op.getRhs();

    auto bc = rhs.getDefiningOp<mlir::triton::BroadcastOp>();
    if (!bc)
      return failure();

    Value s = bc.getSrc();
    // Compute recip(s) as 1/s with a splat constant matching s's shape
    auto shapedTy = dyn_cast<ShapedType>(s.getType());
    if (!shapedTy || !llvm::isa<FloatType>(shapedTy.getElementType()))
      return failure();
    auto oneElem = rewriter.getFloatAttr(shapedTy.getElementType(), 1.0);
    auto oneAttr = SplatElementsAttr::get(shapedTy, oneElem);
    auto one = rewriter.create<arith::ConstantOp>(op.getLoc(), oneAttr);
    auto recip = rewriter.create<arith::DivFOp>(op.getLoc(), one, s);
    // broadcast recip to match rhs type
    auto recipBc = rewriter.create<mlir::triton::BroadcastOp>(op.getLoc(), rhs.getType(), recip);
    auto mul = rewriter.create<arith::MulFOp>(op.getLoc(), lhs, recipBc);
    rewriter.replaceOp(op, mul.getResult());
    return success();
  }
};

struct TritonSoftmaxMicroOpts
    : public impl::TritonSoftmaxMicroOptsBase<TritonSoftmaxMicroOpts> {
  void runOnOperation() override {
    MLIRContext *context = &getContext();
    RewritePatternSet patterns(context);
    patterns.add<DivToMulRecip>(context);

    GreedyRewriteConfig config;
    if (failed(applyPatternsGreedily(getOperation(), std::move(patterns), config)))
      signalPassFailure();
  }
};

} // namespace

// Factory function is generated by TableGen in Passes.h.inc

} // namespace triton
} // namespace mlir
